[WIP]メッセージ機能の実装
kotasugimoto/chat-space3 pull request #6
Opened 2016-10-24 05:28 UTC by kotasugimoto

2016-10-24 07:53 UTC, kotasugimoto commented
![default](https://cloud.githubusercontent.com/assets/22768629/19637501/60d85378-9a0a-11e6-9aac-cc8208f0f921.png)

2016-10-25 02:54 UTC, naokishizuka commented on app/controllers/messages_controller.rb
> +		@message = Message.create(message_params)
message.create(message_params)
とすると、この時点でsaveまでされてしまいますので
message.new(message_params)
としましょう。

2016-10-25 02:56 UTC, naokishizuka commented on app/controllers/messages_controller.rb
> +        else
インデントが所々連れている箇所がございますので、きっちりとそろえてあげましょう。
可読性を高めることでバグを減らすことができます。

2016-10-25 03:07 UTC, naokishizuka commented on app/controllers/messages_controller.rb
> +	        render:index
こちらは正常に動いていますでしょうか？

2016-10-25 03:44 UTC, naokishizuka commented on app/controllers/messages_controller.rb
> +	@message = Message.create(message_params)
Message.new(message_params)
に変更しましょう。

2016-10-25 03:44 UTC, naokishizuka commented on app/controllers/messages_controller.rb
> +    else
elseとifの高さは揃えましょう。

2016-10-25 03:55 UTC, naokishizuka commented on app/controllers/messages_controller.rb
>      end
if else end
は三つで機能しているまとまりですので高さを揃える必要があります。

2016-10-25 03:58 UTC, naokishizuka commented on app/controllers/messages_controller.rb
> +	@message = Message.create(message_params)
Message.new(message_params)
に変更しましょう。

2016-10-25 04:31 UTC, hc0208 requested changes

2016-10-25 04:31 UTC, hc070208 commented on app/controllers/messages_controller.rb
> +	  render:index
```
render :index
```
renderと:indexの間にスペースを入れていただきたいです。

2016-10-25 04:33 UTC, merged